name: Bug Report
description: Report a bug or unexpected behavior in ununseptium
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the form below with as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Ununseptium Version
      description: What version of ununseptium are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      placeholder: "3.11"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - KYC (Identity Verification)
        - AML (Transaction Monitoring)
        - Security (PII, Encryption, Audit)
        - MathStats (Conformal, EVT, Hawkes)
        - AI (Models, Features, Explainability)
        - CLI
        - Core
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install ununseptium...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: If applicable, provide a minimal code example that reproduces the issue.
      render: python
      placeholder: |
        from ununseptium import ...

        # Code that reproduces the issue

  - type: textarea
    id: error
    attributes:
      label: Error Message / Traceback
      description: If applicable, paste the full error message or traceback.
      render: text
      placeholder: Paste error message here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug has not been reported before.
          required: true
        - label: I have provided all requested information.
          required: true
        - label: I am using a supported Python version (3.11+).
          required: true
